const States = () => {

    const states = [
        'Alabama',
        'Alaska',
        'Arizona',
        'Arkansas',
        'California',
        'Colorado',
        'Connecticut',
        'Delaware',
        'Florida',
        'Georgia',
        'Hawaii',
        'Idaho',
        'Illinois',
        'Indiana',
        'Iowa',
        'Kansas',
        'Kentucky[E]',
        'Louisiana',
        'Maine',
        'Maryland',
        'Massachusetts[E]',
        'Michigan',
        'Minnesota',
        'Mississippi',
        'Missouri',
        'Montana',
        'Nebraska',
        'Nevada',
        'New Hampshire',
        'New Jersey',
        'New Mexico',
        'New York',
        'North Carolina',
        'North Dakota',
        'Ohio',
        'Oklahoma',
        'Oregon',
        'Pennsylvania[E]',
        'Rhode Island[F]',
        'South Carolina',
        'South Dakota',
        'Tennessee',
        'Texas',
        'Utah',
        'Vermont',
        'Virginia[E]',
        'Washington',
        'West Virginia',
        'Wisconsin',
        'Wyoming',
        'District of Columbia',
        'American Samoa',
        'Guam',
        'Northern Mariana Islands',
        'Puerto Rico',
        'U.S. Virgin Islands',
        'Baker Island',
        'Howland Island',
        'Jarvis Island',
        'Johnston Atoll',
        'Kingman Reef',
        'Midway Atoll',
        'Navassa Island',
        'Palmyra Atoll',
        'Wake Island'
    ]

    return (
        states.map(state => {
            return <option>{state}</option>
        })
    )
}

export default States